/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "cloudata_constants.h"

namespace cloudata {

const cloudataConstants g_cloudata_constants;

cloudataConstants::cloudataConstants() {
}

} // namespace

