/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef cloudata_CONSTANTS_H
#define cloudata_CONSTANTS_H

#include "cloudata_types.h"

namespace cloudata {

class cloudataConstants {
 public:
  cloudataConstants();

};

extern const cloudataConstants g_cloudata_constants;

} // namespace

#endif
