/* Generated By:JavaCC: Do not edit this line. CqlParserConstants.java */
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.cloudata.core.client.cql.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CREATE = 5;
  /** RegularExpression Id. */
  int TABLE = 6;
  /** RegularExpression Id. */
  int VERSION = 7;
  /** RegularExpression Id. */
  int COMMENT = 8;
  /** RegularExpression Id. */
  int DROP = 9;
  /** RegularExpression Id. */
  int SELECT = 10;
  /** RegularExpression Id. */
  int FROM = 11;
  /** RegularExpression Id. */
  int INTO = 12;
  /** RegularExpression Id. */
  int WHERE = 13;
  /** RegularExpression Id. */
  int LIKE = 14;
  /** RegularExpression Id. */
  int BETWEEN = 15;
  /** RegularExpression Id. */
  int IN = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int OR = 18;
  /** RegularExpression Id. */
  int NOT = 19;
  /** RegularExpression Id. */
  int TIMESTAMP = 20;
  /** RegularExpression Id. */
  int INSERT = 21;
  /** RegularExpression Id. */
  int VALUES = 22;
  /** RegularExpression Id. */
  int DELETE = 23;
  /** RegularExpression Id. */
  int ADD = 24;
  /** RegularExpression Id. */
  int USER = 25;
  /** RegularExpression Id. */
  int COMMA = 26;
  /** RegularExpression Id. */
  int DOT = 27;
  /** RegularExpression Id. */
  int STAR = 28;
  /** RegularExpression Id. */
  int LEFT_PAREN = 29;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 30;
  /** RegularExpression Id. */
  int EQ = 31;
  /** RegularExpression Id. */
  int GT = 32;
  /** RegularExpression Id. */
  int LT = 33;
  /** RegularExpression Id. */
  int GT_EQ = 34;
  /** RegularExpression Id. */
  int LT_EQ = 35;
  /** RegularExpression Id. */
  int REAL_NUM = 36;
  /** RegularExpression Id. */
  int INT_NUM = 37;
  /** RegularExpression Id. */
  int DIGIT = 38;
  /** RegularExpression Id. */
  int IDENTIFIER = 39;
  /** RegularExpression Id. */
  int LETTER = 40;
  /** RegularExpression Id. */
  int STRING_LITERAL = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"CREATE\"",
    "\"TABLE\"",
    "\"VERSION\"",
    "\"COMMENT\"",
    "\"DROP\"",
    "\"SELECT\"",
    "\"FROM\"",
    "\"INTO\"",
    "\"WHERE\"",
    "\"LIKE\"",
    "\"BETWEEN\"",
    "\"IN\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "\"TIMESTAMP\"",
    "\"INSERT\"",
    "\"VALUES\"",
    "\"DELETE\"",
    "\"ADD\"",
    "\"USER\"",
    "\",\"",
    "\".\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "<REAL_NUM>",
    "<INT_NUM>",
    "<DIGIT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<STRING_LITERAL>",
  };

}
